### ISSUE TITLE
Something murdered FPS in recent commits

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Voxel-demo#65]
Something has absolutely murdered the FPS in recent commits.

It is now around 6-10 all of the time.

I would probably start by looking into the player character.

**Comment by Pawlost** [comment]
I found that reason for this bug was wrong culling. I fixed everything in recent commit in dev branch, but we dont know if we will use it because it may be slower. We need to test it on Pilvinens PC but it doesnt work due to this https://github.com/starandserpent/Voxel-demo/issues/86 issue.

**Comment by Pilvinen** [comment]
Confirmed. The issue is resolved by the mesher rewrite.
