### ISSUE TITLE
Investigate mesh generation - we might be getting extra geometry

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Voxel-demo#76]
Someone needs to check whether mesh generation is working as it should.

I'm getting a minimum of 72 vertices per chunk (apparently?) in situations where there should be either 8 vertices (assuming a single chunk) or 64 vertices (in case there are actually 8 chunks in the scene).

I set the world size to 1 1 1 and it crashed.

I set the world size to 2 2 2 and I get 72 vertices in view no matter what view position/angle I use. So I'm assuming what I'm seeing is one flat chunk of homogeneous material - with 72 vertices for some reason.

If there are indeed about ~8-9x the amount of vertices there should be it would go a long way in explaining the FPS performance degradation we've been experiencing recently.

In either case I cannot think of a situation which would explain why there are 72 vertices as opposed to either 64 or 8.

**Comment by Pawlost** [comment]
This is actualy correct amount, I am putting more vertices to scene to make generation of colliders faster. Godot throwed error if vertex, index and texture amount in array wasnt same. This may be fixed in newer version and if it is, reducing this amount could make everything faster.

**Comment by Pawlost** [comment]
Anyway calculation is 6 vertex per side, 6 sides for both colliders and meshes. 6x6x2 = 72

**Comment by Pawlost** [comment]
OK the error was different. Collider throwed error but normal mesh can have different amount of indexes. Since I need to seperate Colliders https://github.com/starandserpent/Voxel-demo/issues/88 I am using only 4 vetrices now.
