### ISSUE TITLE
Tool for measuring distance

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Voxel-demo#94]
I need a tool which shoots laser beam from the eyes of the camera to a target and gives two numbers:

1) Distance in as a straight line between A and B.

2) Distance in as a horizontal (flat, no Y taken into account) line between A and B.

I want the distance in meters when it's under 1000 meters and when it's above 1000 meters I want it as kilometers.

**Comment by Pawlost** [comment]
This issue is duplicate of this https://github.com/starandserpent/Voxel-demo/issues/57
