### ISSUE TITLE
Keep track of Real memory usage and show it in Debug HUD 

### ISSUE THREAD

**Issue by Pilvinen** [starandserpent/Voxel-demo#97]
I looked into it a bit and if it's outside of GC we have to keep track of all native memory allocations ourselves.

If it's happening in memory managed by the GC we should be able to get information from: `GC.GetGCMemoryInfo`

Slightly in passing the subject there's also something called `GC.AddMemoryPressure` which informs the GC of allocations made in native memory so it can plan it's GC better, which might be important to us.

We only need to poll the memory usage once per second or less.

If that  seems unsmooth there's also a possibility of polling and caching for a while before showing anything, and then calculating and displaying averages of the situation moments ago at a faster frequency.

This produces "accurate enough" memory values which appear to be updating at a faster rate than they truly are.

**Comment by Pawlost** [comment]
Memory from GC is showed. The rest is different issue.
